version: '3'

services:
  appscope01:
    container_name: appscope01
    image: "cribl/scope:${APPSCOPE_VERSION:-1.1.1}"
    volumes:
      - shared-appscope:/usr/local/lib

  redis01:
    container_name: redis01
    restart: always
    image: "redis:${REDIS_VERSION:-7.0.4}"
    environment:
      - LD_PRELOAD=/usr/local/lib/libscope.so
    volumes:
      - /var/run/appscope:/var/run/appscope
      - shared-appscope:/usr/local/lib

  # redis02:
  #   container_name: redis02
  #   restart: always
  #   image: "redis:${REDIS_VERSION:-7.0.4}-alpine"
  #   environment:
  #     - LD_PRELOAD=/usr/local/lib/libscope.so
  #   volumes:
  #     - /var/run/appscope:/var/run/appscope
  #     - shared-appscope:/usr/local/lib

  edge01:  
    container_name: edge01
    image: "cribl/cribl:${EDGE_VERSION:-3.5.0}"
    privileged: true
    environment:
      - CRIBL_EDGE=1
    ports:
      - "${EDGE_UI_PORT:-9420}:${EDGE_UI_PORT:-9420}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/appscope:/var/run/appscope

volumes:
  shared-appscope:
